import type { Metadata } from "next";
import "./globals.css";
import Banner from "./pages/Banner";
import Header from "./components/Header";
import { Open_Sans } from 'next/font/google'

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      {/* Apply the Roboto font class */}
      <body className={`${openSans.className} relative`}>
        <Header />
        <Banner />
      </body>
    </html>
  );
}
